export function getDefaultPedidoValues(pedido) {
  return {
    tipo: 'Pedido',
    tipo_pedido: 'Misto',
    origem_pedido: (pedido && pedido.origem_pedido) ? pedido.origem_pedido : 'Manual',
    status: 'Rascunho',
    data_pedido: new Date().toISOString().split('T')[0],
    prioridade: 'Normal',
    itens_revenda: [],
    itens_armado_padrao: [],
    itens_corte_dobra: [],
    endereco_entrega_principal: {},
    forma_pagamento: 'À Vista',
    valor_total: 0,
    valor_produtos: 0,
    peso_total_kg: 0,
    percentual_conclusao_wizard: 0,
    etapa_atual_wizard: 1,
    cliente_id: '',
    cliente_nome: '',
    numero_pedido: '',
    empresa_id: '',
    projetos_ia: [],
    anexos: [],
    desconto_geral_pedido_percentual: 0,
    desconto_geral_pedido_valor: 0,
    valor_frete: 0,
    etapas_entrega: [],
    obra_destino_id: '',
    obra_destino_nome: '',
    observacoes_nfe: '',
  };
}