const markdown = [
  "# Inventário — Administração do Sistema",
  "",
  "## Abas principais",
  "- `gerais` → `ConfiguracoesGeraisIndex` → `ConfigGlobal`",
  "- `integracoes` → `IntegracoesIndex`",
  "- `acessos` → `GestaoAcessosIndex`",
  "- `seguranca` → `SegurancaGovernancaIndex`",
  "- `ia` → `IAOtimizacaoIndex`",
  "- `auditoria` → `AuditoriaLogsIndex`",
  "- `ferramentas` → `AdminFerramentas`",
  "",
  "## Inventário operacional da área",
  "- Tabs principais: gerais, integracoes, acessos, seguranca, ia, auditoria e ferramentas (admin).",
  "- Componentes-mãe já existentes: `AdminTabs`, `ConfiguracoesGeraisIndex`, `IntegracoesIndex`, `GestaoAcessosIndex`, `SegurancaGovernancaIndex`, `IAOtimizacaoIndex`, `AuditoriaLogsIndex`.",
  "- Comandos de navegação: troca de aba por URL `?tab=`, `TabsTrigger`, `ProtectedSection` por módulo/seção.",
  "- Ações administrativas: seed, backfill dry-run, backfill apply.",
  "- Ações de integrações: criar estrutura base, testar webhook, simular NF-e autorizada.",
  "- Toggles-mãe já identificados: segurança, IA, backup, criptografia, fiscal e notificações.",
  "- Camada atual de leitura/gravação: `useConfiguracaoSistema`, `useToggleConfig`, `useConfiguracaoSistema(chave)`, `upsertConfig`, `getEntityRecord`.",
  "- Regras transversais já presentes: RBAC com `ProtectedSection`, escopo grupo/empresa com `useContextoVisual`, auditoria com `AuditLog` e `auditError`.",
  "",
  "## Mapa chave → função real",
  "",
  "### Segurança",
  "- `seg_login_duplo_fator`",
  "  - Tela: `ConfigGlobal > Segurança`",
  "  - Alias visual: `cc_exigir_mfa` em `ConfigCenter`",
  "  - Função real: `functions/verifyTotp`",
  "  - Efeito esperado: exigir MFA no fluxo de validação/login",
  "  - Escopo: grupo/empresa/global",
  "",
  "- `seg_bloquear_ip_suspeito`",
  "  - Tela: `ConfigGlobal > Segurança`",
  "  - Alias visual: `cc_bloquear_ips_suspeitos` em `ConfigCenter`",
  "  - Função real: `functions/entityGuard`",
  "  - Efeito esperado: bloquear tráfego/IP suspeito",
  "  - Escopo: grupo/empresa/global",
  "",
  "- `seg_auditoria_detalhada`",
  "  - Tela: `ConfigGlobal > Segurança`",
  "  - Alias visual: `cc_auditoria_automatica` em `ConfigCenter`",
  "  - Função real: `functions/auditError`",
  "  - Efeito esperado: registrar logs detalhados",
  "  - Escopo: grupo/empresa/global",
  "",
  "- `seg_sessao_unica`",
  "  - Tela: `ConfigGlobal > Segurança`",
  "  - Função real: ainda sem consumo backend confirmado",
  "  - Efeito esperado: impedir múltiplas sessões simultâneas",
  "  - Escopo: grupo/empresa/global",
  "",
  "- `seg_notif_novo_dispositivo`",
  "  - Tela: `ConfigGlobal > Segurança`",
  "  - Função real: ainda sem consumo backend confirmado",
  "  - Efeito esperado: alertar novo dispositivo",
  "  - Escopo: grupo/empresa/global",
  "",
  "- `seg_lgpd_anonimizacao`",
  "  - Tela: `ConfigGlobal > Segurança`",
  "  - Função real: ainda sem consumo backend confirmado",
  "  - Efeito esperado: anonimização automática",
  "  - Escopo: grupo/empresa/global",
  "",
  "### IA e Segurança IA",
  "- `cc_ia_seguranca_ativa`",
  "  - Tela: `ConfigCenter > Segurança`",
  "  - Alias backend: `seg_ia_seguranca`",
  "  - Função real: `functions/securityAlerts`",
  "  - Efeito esperado: habilitar análise/alertas de segurança",
  "  - Escopo: grupo/empresa/global",
  "",
  "- `ia_leitura_projetos`",
  "  - Tela: `IAOtimizacaoIndex`",
  "  - Função real: `InvokeLLM` / leitura assistida de projetos (mapeamento pendente por módulo)",
  "  - Efeito esperado: habilitar leitura inteligente de projetos e anexos",
  "  - Escopo: grupo/empresa",
  "",
  "- `ia_preditiva_vendas`",
  "  - Tela: `IAOtimizacaoIndex`",
  "  - Função real: `oportunidadeScorer` / `iaChurnAnalyzer` / previsões comerciais",
  "  - Efeito esperado: permitir previsão comercial e priorização",
  "  - Escopo: grupo/empresa",
  "",
  "- `ia_conciliacao`",
  "  - Tela: `IAOtimizacaoIndex`",
  "  - Função real: `iaFinanceAnomalyScan` / conciliação assistida",
  "  - Efeito esperado: ativar automações e leitura inteligente no financeiro",
  "  - Escopo: grupo/empresa",
  "",
  "- `ia_producao`",
  "  - Tela: `IAOtimizacaoIndex`",
  "  - Função real: `optimizerOrchestrator` / módulos de produção",
  "  - Efeito esperado: habilitar otimização e apoio à produção",
  "  - Escopo: grupo/empresa",
  "",
  "- `ia_recomendacao_produtos`",
  "  - Tela: `IAOtimizacaoIndex`",
  "  - Função real: `productPriceOptimizer` / motores de recomendação",
  "  - Efeito esperado: habilitar recomendação e apoio de catálogo/vendas",
  "  - Escopo: grupo/empresa",
  "",
  "- `ia_anomalia_financeira`",
  "  - Tela: `IAOtimizacaoIndex`",
  "  - Função real: `iaFinanceAnomalyScan`",
  "  - Efeito esperado: cada módulo consultar antes de executar IA financeira",
  "  - Escopo: grupo/empresa",
  "",
  "### Backup e dados",
  "- `cc_backup_automatico`",
  "  - Tela: `ConfigCenter > Backup & Logs`",
  "  - Função real: `functions/autoBackup`",
  "  - Efeito esperado: habilitar rotina de backup",
  "  - Escopo: grupo/empresa/global",
  "",
  "- `cc_criptografia_dados`",
  "  - Tela: `ConfigCenter > Backup & Logs`",
  "  - Função real: `functions/piiEncryptor`",
  "  - Efeito esperado: criptografia de dados sensíveis",
  "  - Escopo: grupo/empresa/global",
  "",
  "### Notificações",
  "- `notif_pedido_aprovado`",
  "  - Tela: `ConfigGlobal > Notificações`",
  "  - Função real: `functions/onPedidoApprovalRequested`",
  "  - Efeito esperado: avisar aprovação/solicitação de pedido",
  "  - Escopo: grupo/empresa/global",
  "",
  "- `notif_entrega_transporte`",
  "  - Tela: `ConfigGlobal > Notificações`",
  "  - Função real: `functions/onEntregaUpdated`",
  "  - Efeito esperado: avisar eventos de expedição/transporte",
  "  - Escopo: grupo/empresa/global",
  "",
  "- `notif_boleto_gerado`",
  "  - Tela: `ConfigGlobal > Notificações`",
  "  - Função real: `functions/emitirBoleto`",
  "  - Efeito esperado: avisar geração de cobrança/boleto",
  "  - Escopo: grupo/empresa/global",
  "",
  "- `notif_titulo_vencido`",
  "  - Tela: `ConfigGlobal > Notificações`",
  "  - Função real: `functions/paymentStatusManager`",
  "  - Efeito esperado: avisar atraso e mudança de status financeiro",
  "  - Escopo: grupo/empresa/global",
  "",
  "- `notif_op_atrasada`",
  "  - Tela: `ConfigGlobal > Notificações`",
  "  - Função real: precisa conexão final com produção/automação",
  "  - Efeito esperado: alertar atrasos de ordem de produção",
  "  - Escopo: grupo/empresa/global",
  "",
  "- `notif_estoque_baixo`",
  "  - Tela: `ConfigGlobal > Notificações`",
  "  - Função real: precisa conexão final com estoque/alertas",
  "  - Efeito esperado: alertar estoque crítico",
  "  - Escopo: grupo/empresa/global",
  "",
  "### Fiscal",
  "- `fiscal_cfop_interno`",
  "  - Tela: `ConfigGlobal > Fiscal`",
  "  - Função real: `functions/nfeActions`",
  "  - Efeito esperado: definir CFOP interno padrão nas emissões",
  "  - Escopo: grupo/empresa/global",
  "",
  "- `fiscal_cfop_externo`",
  "  - Tela: `ConfigGlobal > Fiscal`",
  "  - Função real: `functions/nfeActions`",
  "  - Efeito esperado: definir CFOP externo padrão nas emissões",
  "  - Escopo: grupo/empresa/global",
  "",
  "- `fiscal_aliq_icms`",
  "  - Tela: `ConfigGlobal > Fiscal`",
  "  - Função real: fluxos fiscais e cálculo tributário",
  "  - Efeito esperado: parametrizar ICMS padrão",
  "  - Escopo: grupo/empresa/global",
  "",
  "- `fiscal_aliq_pis`",
  "  - Tela: `ConfigGlobal > Fiscal`",
  "  - Função real: fluxos fiscais e cálculo tributário",
  "  - Efeito esperado: parametrizar PIS padrão",
  "  - Escopo: grupo/empresa/global",
  "",
  "- `fiscal_aliq_cofins`",
  "  - Tela: `ConfigGlobal > Fiscal`",
  "  - Função real: fluxos fiscais e cálculo tributário",
  "  - Efeito esperado: parametrizar COFINS padrão",
  "  - Escopo: grupo/empresa/global",
  "",
  "- `fiscal_obs_nfe`",
  "  - Tela: `ConfigGlobal > Fiscal`",
  "  - Função real: `functions/nfeActions`",
  "  - Efeito esperado: preencher observações complementares da NF-e",
  "  - Escopo: grupo/empresa/global",
  "",
  "## Ações e botões críticos já encontrados",
  "- `AdminFerramentas > Executar Seed Leve` → `functions/seedData`",
  "- `AdminFerramentas > Dry-run` → `functions/backfillGroupEmpresa`",
  "- `AdminFerramentas > Aplicar Correções` → `functions/backfillGroupEmpresa`",
  "- `IntegracoesIndex > Criar estrutura base` → `functions/upsertConfig`",
  "- `IntegracoesIndex > Testar webhook Asaas` → `functions/legacyIntegrationsMirror`",
  "- `IntegracoesIndex > Simular NF-e autorizada` → `functions/legacyIntegrationsMirror`",
  "",
  "## Botões, ações e estados obrigatórios",
  "- Todo botão crítico deve passar por `entityGuard` direta ou indiretamente.",
  "- Toda ação sensível deve respeitar RBAC, contexto empresa/grupo e auditoria.",
  "- Toda ação precisa expor feedback visual: carregando, sucesso, erro ou bloqueio.",
  "- Todo módulo deve consultar configuração antes de executar funções sensíveis/IA.",
  "",
  "## Cobertura já conectada",
  "- `seg_auditoria_detalhada` / `cc_auditoria_automatica` → `functions/auditError`",
  "- `seg_login_duplo_fator` / `cc_exigir_mfa` → `functions/verifyTotp`",
  "- `seg_bloquear_ip_suspeito` / `cc_bloquear_ips_suspeitos` → `functions/entityGuard`",
  "- `cc_ia_seguranca_ativa` / `seg_ia_seguranca` → `functions/securityAlerts`",
  "- `cc_backup_automatico` → `functions/autoBackup`",
  "- `cc_criptografia_dados` → `functions/piiEncryptor`",
  "",
  "## Fluxo recomendado de fechamento",
  "1. Administração do Sistema",
  "2. Segurança e IA",
  "3. Integrações",
  "4. Cadastros",
  "5. Financeiro",
  "6. Comercial",
  "7. Estoque",
  "8. Produção",
  "9. Expedição",
  "",
  "## Próximos passos recomendados",
  "1. Padronizar leitura por helper único para frontend e backend.",
  "2. Auditar consumo real das chaves sem vínculo confirmado.",
  "3. Mapear botões por RBAC, escopo, estado desabilitado e auditoria.",
  "4. Validar por fluxo: Segurança, IA, Integrações, Cadastros, Financeiro, Comercial, Estoque, Produção e Expedição.",
  "5. Fechar Administração do Sistema como fonte única antes dos demais módulos.",
];

export default markdown.join("\n");