const documentationMirrorPatterns = [
  "**/*.md",
  "**/*.json",
  "**/*.config",
  "**/*.md.*",
  "**/*.json.*",
  "**/*.config.*",
  "**/*.md.jsx",
  "**/*.json.jsx",
  "src/**/*.md.jsx",
  "src/**/*.json.jsx",
  "src/**/README*.jsx",
  "src/**/CERTIFIC*.jsx",
  "src/**/CHECKLIST*.jsx",
  "src/**/BLOQUEIO*.jsx",
  "src/**/BOTOES*.jsx",
  "**/commitlint.config.jsx",
  "**/src/**/*.md",
  "**/src/**/*.json",
  "**/src/**/*.config",
  "**/src/**/*.md.*",
  "**/src/**/*.json.*",
  "**/src/**/*.config.*",
  "**/src/**/README*",
  "**/src/**/CERTIFICADO*",
  "**/src/**/CERTIFICACAO*",
  "**/src/**/MANIFESTO*",
  "**/src/**/STATUS*",
  "**/src/**/VALIDACAO*",
  "**/src/**/CHECKLIST*",
  "**/src/**/ETAPA*",
  "**/src/**/FASE*",
  "**/src/**/PROVA*",
  "**/src/**/SISTEMA*",
  "**/src/**/MIGRACAO*",
  "**/src/**/BLOQUEIO*",
  "**/src/**/DEBUG*",
  "**/src/**/DIAGNOSTICO*",
  "**/src/**/INTEGRACAO*",
  "**/src/**/RESUMO*",
  "**/src/**/CHANGELOG*",
  "**/src/**/ROADMAP*",
  "**/src/**/GUIA*",
  "**/src/**/DOC*",
  "**/src/**/UnidadesDeMedida*",
  "**/src/**/rhf_zod_report*",
  "**/components/**/README*",
  "**/components/**/CERTIFICADO*",
  "**/components/**/CERTIFICACAO*",
  "**/components/**/MANIFESTO*",
  "**/components/**/STATUS*",
  "**/components/**/VALIDACAO*",
  "**/components/**/CHECKLIST*",
  "**/components/**/ETAPA*",
  "**/components/**/FASE*",
  "**/components/**/PROVA*",
  "**/components/**/SISTEMA*",
  "**/components/**/BLOQUEIO*",
  "**/components/**/BOTOES*",
  "**/components/**/INTEGRACAO*",
  "**/components/**/UnidadesDeMedida*",
  "**/components/**/rhf_zod_report*",
];

export default [
  {
    ignores: [
      "dist/**",
      "build/**",
      "node_modules/**",
      ...documentationMirrorPatterns,
    ],
  },
  {
    files: ["src/**/*.{js,jsx}", "*.{js,jsx}"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      parserOptions: {
        ecmaFeatures: { jsx: true },
      },
      globals: {
        window: "readonly",
        document: "readonly",
        navigator: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        console: "readonly",
        setTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        Blob: "readonly",
        URL: "readonly",
        confirm: "readonly",
        prompt: "readonly",
        React: "readonly",
      },
    },
    rules: {
      "no-undef": "error",
    },
  },
];