export const TOGGLE_MAP_DATA = [
  {
    categoria: 'Segurança',
    chave: 'seg_login_duplo_fator',
    aliases: ['cc_exigir_mfa'],
    tela: 'ConfigGlobal > Segurança / ConfigCenter > Segurança',
    funcao: 'verifyTotp',
    efeito: 'Exigir MFA no fluxo de verificação',
    modulo: 'Sistema',
    escopo: 'grupo/empresa/global',
    status: 'conectado'
  },
  {
    categoria: 'Segurança',
    chave: 'seg_bloquear_ip_suspeito',
    aliases: ['cc_bloquear_ips_suspeitos'],
    tela: 'ConfigGlobal > Segurança / ConfigCenter > Segurança',
    funcao: 'entityGuard',
    efeito: 'Bloquear acesso suspeito por IP/comportamento',
    modulo: 'Sistema',
    escopo: 'grupo/empresa/global',
    status: 'conectado'
  },
  {
    categoria: 'Segurança',
    chave: 'seg_auditoria_detalhada',
    aliases: ['cc_auditoria_automatica'],
    tela: 'ConfigGlobal > Segurança / ConfigCenter > Segurança',
    funcao: 'auditError',
    efeito: 'Gravar logs detalhados de erro e auditoria',
    modulo: 'Sistema',
    escopo: 'grupo/empresa/global',
    status: 'conectado'
  },
  {
    categoria: 'Segurança',
    chave: 'seg_sessao_unica',
    aliases: [],
    tela: 'ConfigGlobal > Segurança',
    funcao: 'não conectado',
    efeito: 'Bloquear múltiplas sessões simultâneas',
    modulo: 'Sistema',
    escopo: 'grupo/empresa/global',
    status: 'pendente'
  },
  {
    categoria: 'Segurança',
    chave: 'seg_notif_novo_dispositivo',
    aliases: [],
    tela: 'ConfigGlobal > Segurança',
    funcao: 'não conectado',
    efeito: 'Notificar novo dispositivo/sessão',
    modulo: 'Sistema',
    escopo: 'grupo/empresa/global',
    status: 'pendente'
  },
  {
    categoria: 'Segurança',
    chave: 'seg_lgpd_anonimizacao',
    aliases: [],
    tela: 'ConfigGlobal > Segurança',
    funcao: 'não conectado',
    efeito: 'Anonimização automática de dados',
    modulo: 'Sistema',
    escopo: 'grupo/empresa/global',
    status: 'pendente'
  },
  {
    categoria: 'IA',
    chave: 'seg_ia_seguranca',
    aliases: ['cc_ia_seguranca_ativa'],
    tela: 'ConfigCenter > Segurança',
    funcao: 'securityAlerts',
    efeito: 'Rodar análise e alertas de segurança assistidos por IA',
    modulo: 'Sistema',
    escopo: 'grupo/empresa/global',
    status: 'conectado'
  },
  {
    categoria: 'IA',
    chave: 'ia_leitura_projetos',
    aliases: ['cc_ia_leitura_projetos'],
    tela: 'IA & Otimização / ConfigCenter > IA',
    funcao: 'mapeamento parcial',
    efeito: 'Habilitar leitura inteligente de projetos',
    modulo: 'IA',
    escopo: 'grupo/empresa',
    status: 'pendente'
  },
  {
    categoria: 'IA',
    chave: 'ia_preditiva_vendas',
    aliases: ['cc_ia_preditiva_vendas'],
    tela: 'IA & Otimização / ConfigCenter > IA',
    funcao: 'oportunidadeScorer / iaChurnAnalyzer',
    efeito: 'Ativar previsão comercial e churn',
    modulo: 'CRM/Comercial',
    escopo: 'grupo/empresa',
    status: 'pendente'
  },
  {
    categoria: 'IA',
    chave: 'ia_conciliacao',
    aliases: ['cc_ia_conciliacao'],
    tela: 'IA & Otimização / ConfigCenter > IA',
    funcao: 'iaFinanceAnomalyScan',
    efeito: 'Ativar análise financeira e conciliação assistida',
    modulo: 'Financeiro',
    escopo: 'grupo/empresa',
    status: 'pendente'
  },
  {
    categoria: 'IA',
    chave: 'ia_producao',
    aliases: ['cc_ia_producao'],
    tela: 'IA & Otimização / ConfigCenter > IA',
    funcao: 'optimizerOrchestrator',
    efeito: 'Ativar otimização produtiva',
    modulo: 'Produção',
    escopo: 'grupo/empresa',
    status: 'pendente'
  },
  {
    categoria: 'Backup',
    chave: 'cc_backup_automatico',
    aliases: [],
    tela: 'ConfigCenter > Backup & Logs',
    funcao: 'autoBackup',
    efeito: 'Habilitar rotina de backup',
    modulo: 'Sistema',
    escopo: 'grupo/empresa/global',
    status: 'conectado'
  },
  {
    categoria: 'Segurança',
    chave: 'cc_criptografia_dados',
    aliases: [],
    tela: 'ConfigCenter > Backup & Logs',
    funcao: 'piiEncryptor',
    efeito: 'Criptografar dados sensíveis',
    modulo: 'Sistema',
    escopo: 'grupo/empresa/global',
    status: 'conectado'
  },
  {
    categoria: 'Notificações',
    chave: 'notif_pedido_aprovado',
    aliases: [],
    tela: 'ConfigGlobal > Notificações',
    funcao: 'onPedidoApprovalRequested',
    efeito: 'Notificar aprovação de pedido',
    modulo: 'Comercial',
    escopo: 'grupo/empresa/global',
    status: 'pendente'
  },
  {
    categoria: 'Notificações',
    chave: 'notif_entrega_transporte',
    aliases: [],
    tela: 'ConfigGlobal > Notificações',
    funcao: 'onEntregaUpdated',
    efeito: 'Notificar eventos de entrega/transporte',
    modulo: 'Expedição',
    escopo: 'grupo/empresa/global',
    status: 'pendente'
  },
  {
    categoria: 'Notificações',
    chave: 'notif_boleto_gerado',
    aliases: [],
    tela: 'ConfigGlobal > Notificações',
    funcao: 'emitirBoleto',
    efeito: 'Notificar geração de boleto/PIX',
    modulo: 'Financeiro',
    escopo: 'grupo/empresa/global',
    status: 'pendente'
  },
  {
    categoria: 'Notificações',
    chave: 'notif_titulo_vencido',
    aliases: [],
    tela: 'ConfigGlobal > Notificações',
    funcao: 'paymentStatusManager',
    efeito: 'Notificar inadimplência/títulos vencidos',
    modulo: 'Financeiro',
    escopo: 'grupo/empresa/global',
    status: 'pendente'
  },
  {
    categoria: 'Fiscal',
    chave: 'fiscal_cfop_interno',
    aliases: [],
    tela: 'ConfigGlobal > Fiscal',
    funcao: 'nfeActions',
    efeito: 'Definir CFOP interno padrão',
    modulo: 'Fiscal',
    escopo: 'grupo/empresa/global',
    status: 'pendente'
  },
  {
    categoria: 'Fiscal',
    chave: 'fiscal_cfop_externo',
    aliases: [],
    tela: 'ConfigGlobal > Fiscal',
    funcao: 'nfeActions',
    efeito: 'Definir CFOP externo padrão',
    modulo: 'Fiscal',
    escopo: 'grupo/empresa/global',
    status: 'pendente'
  }
];